from __future__ import annotations

from algohlper.models import ArtifactRecord, ProblemSpec, ProjectRecord


def build_starter_artifacts(project: ProjectRecord, spec: ProblemSpec) -> dict[str, ArtifactRecord]:
    return {
        "brute": ArtifactRecord(type="brute", language="cpp", code=build_brute_template(spec)),
        "generator": ArtifactRecord(type="generator", language="cpp", code=build_generator_template(spec)),
        "compare": ArtifactRecord(type="compare", language="python", code=build_compare_script()),
        "readme": ArtifactRecord(type="readme", language="markdown", code=build_repro_readme(project, spec)),
    }


def build_brute_template(spec: ProblemSpec) -> str:
    constraints = _format_constraints_comment(spec)
    samples = _format_samples_comment(spec)
    return f"""#include <bits/stdc++.h>
using namespace std;

// Starter brute template generated by AlgoHlper.
// TODO: 把这里改成“小数据正确性优先”的参考解。
// 题目：{spec.title}
// 约束：
{constraints}
// 样例：
{samples}

int main() {{
    ios::sync_with_stdio(false);
    cin.tie(nullptr);

    // TODO: 读取输入。
    // TODO: 编写正确性优先的参考解。
    return 0;
}}
"""


def build_generator_template(spec: ProblemSpec) -> str:
    constraints = _format_constraints_comment(spec)
    return f"""#include <bits/stdc++.h>
using namespace std;

// Starter generator template generated by AlgoHlper.
// 调用方式：./gen seed mode size
// mode 建议：random / edge / small / adversarial
// TODO: 按题目输入格式补全生成逻辑。
// 题目：{spec.title}
// 约束：
{constraints}

int main(int argc, char** argv) {{
    long long seed = argc > 1 ? atoll(argv[1]) : 1;
    string mode = argc > 2 ? argv[2] : "random";
    int size = argc > 3 ? atoi(argv[3]) : 5;
    mt19937_64 rng(seed);

    // TODO: 根据 mode / size 生成合法输入。
    // 下面只是示例占位，防止空程序。
    cout << 1 << "\\n";
    cout << 0 << "\\n";
    (void)mode;
    (void)size;
    (void)rng;
    return 0;
}}
"""


def build_compare_script() -> str:
    return """from pathlib import Path
import sys


def normalize(text: str) -> str:
    lines = [line.rstrip() for line in text.replace("\\r\\n", "\\n").split("\\n")]
    while lines and lines[-1] == "":
        lines.pop()
    return "\\n".join(lines)


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: python compare.py expected.txt actual.txt")
        return 2
    expected = normalize(Path(sys.argv[1]).read_text(encoding="utf-8"))
    actual = normalize(Path(sys.argv[2]).read_text(encoding="utf-8"))
    if expected == actual:
        print("OK")
        return 0
    print("DIFF")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
"""


def build_repro_readme(project: ProjectRecord, spec: ProblemSpec) -> str:
    return f"""# {project.name}

## Problem
- Title: {spec.title}

## Local reproduction

1. 编辑 `brute.cpp` 与 `gen.cpp`，让它们真正符合题意。
2. 准备你的 `main.cpp`。
3. 编译：

```bash
g++ -O2 -std=c++17 -pipe brute.cpp -o brute
g++ -O2 -std=c++17 -pipe gen.cpp -o gen
g++ -O2 -std=c++17 -pipe main.cpp -o main
```

4. 单轮手工验证：

```bash
./gen 1 random 5 > input.txt
./brute < input.txt > expected.txt
./main < input.txt > actual.txt
python compare.py expected.txt actual.txt
```

## Notes
- 当前仓库里的 starter 资产是模板，不是最终答案。
- 下一步建议接入真实 LLM 生成服务，并保留这里的模板作为 fallback。
"""


def _format_constraints_comment(spec: ProblemSpec) -> str:
    if not spec.constraints:
        return "// - TODO: 根据题面补约束"
    return "\n".join(f"// - {key}: {value}" for key, value in spec.constraints.items())


def _format_samples_comment(spec: ProblemSpec) -> str:
    if not spec.samples:
        return "// - 暂无样例"
    lines: list[str] = []
    for index, sample in enumerate(spec.samples, start=1):
        lines.append(f"// Sample {index} input: {sample.input.replace(chr(10), ' | ')}")
        lines.append(f"// Sample {index} output: {sample.output.replace(chr(10), ' | ')}")
    return "\n".join(lines)
